description: "Server for testing (internal)"

# Папка на клиентском сервере для установки
antor_root_folder: "ANTOR"
disk_install: "C:"

user_antor: "ANTOR-ENTERPRISE"
passw_user_antor: "BfIFq2Rm7g"
user_adm_antor: "antor_admin"
passw_adm_antor: "1q23456&*"

ext_ip_address_host: "192.168.0.48"

# Диапозон портов для телематики
tele_port_range: "2225-2237"

iis_ae_site_port_range: "8093-8095"
http_port_ae_site: "8093"
https_port1_ae_site: "8094"
https_port2_ae_site: "8095"

ftp_folder: "FTP_ANTOR"
ftp_port_range1: "6001"
ftp_port_range2: "7000"
ftp_port: "21"

antor_ent_site: "ANTOR Enterprise"

user_webdav: "AE-MEDIA"
passw_user_webdav: "BfIFq2Rm7g"
webdav_folder: "AE-MEDIA"
webdav_site: "AE_MEDIA"
http_port_webdav: "8101"
https_port_webdav: "8102"

sql_name: "SQL2019"
sql_host: "."
sql_admin: "sa"
sql_passw: "6MbYCXm4NY95BFG6O4dB"
sql_win_admin: "antor_admin"
sql_service: "MSSQL$SQL2019"
