description: "Server for testing (internal)"

# Папка на клиентском сервере для установки
antor_root_folder: "C:\\ANTOR"

user_antor: "ANTOR-ENTERPRISE"
passw_user_antor: "BfIFq2Rm7g"
user_adm_antor: "antor_admin"
pasw_adm_antor: "OAsJj47vwr"

# Диапозон портов для телематики
tele_port_range: "2238-2250"
iis_ae_site_port_range: "8093-8095"
http_port_ae_site: "8090"
https_port1_ae_site: "8091"
https_port2_ae_site: "8092"
