description: "Server for testing (internal)"

# Папка на клиентском сервере для установки
antor_root_folder: "ANTOR"
disk_install: "C:"

user_antor: "ANTOR-ENTERPRISE"
passw_user_antor: "BfIFq2Rm7g"
user_adm_antor: "antor_admin"
pasw_adm_antor: "1q23456&*"

# Диапозон портов для телематики
tele_port_range: "2238-2250"
iis_ae_site_port_range: "8093-8095"
http_port_ae_site: "8093"
https_port1_ae_site: "8094"
https_port2_ae_site: "8095"
