---

#Папка дистрибутива LiW на внутреннем сервере АНТОР
repo_folder: \\\\server\\антор\\Отдел Внедрения\\Релизы\\LogistinWeb\\Repo

#Внешняя папка дистрибутива LiW на внутреннем сервере АНТОР
repo_folder_ext: \\\\tsclient\\V\\Релизы\\LogistinWeb\\Repo

#ftp server c дистрибутивом LiW
ftp_server_repo: "ftp://ans_distr:4M3nONDY2u@192.168.3.4"
ftp_folder_repo: "LiW_repo"



# Имя виртуалки для теста
vm_name: win2k19-liw-test
# Имя snapshot для отката виртуалки в исходное состояние
vm_snapshot: snapshot1


