---
#Папка утилит LiW на внутреннем сервере АНТОР
repo_utils_folder: "{{ repo_folder }}\\Utils"
#Внешняя папка утилит LiW на внутреннем сервере АНТОР
repo_utils_folder_ext: "{{ repo_folder_ext }}\\Utils"
# Имя архива со всеми админскими утилиатми
tools_file_7z: "Utils.7z"
antor_tools_folder: "Utils"
# Список админских утилит с параметрами для установки
tools_list:
  - tool_name: "Background info"
    distr_path: ""
    zip_name: "bginfo.zip"
    exe_name: "Bginfo64.exe"
    path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\bginfo"
    install: false
    install_script: ""
    shortcut: false
    icon_path: ""
  - tool_name: "cports"
    distr_path: ""
    zip_name: "cports.zip"
    exe_name: "cports.exe"
    path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\cports"
    install: true
    install_script: Set-Content -Path "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\cports\\cports_filter.txt" -Value "include:local:tcp:{{ tele_port_range }}"
    shortcut: true
    icon_path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\cports\\cports.exe"
  - tool_name: "totalcmd"
    distr_path: ""
    zip_name: "totalcmd.zip"
    exe_name: "totalcmd.exe"
    path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\totalcmd"
    install: false
    install_script: ""
    shortcut: true
    icon_path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\totalcmd\\totalcmd.exe"
  - tool_name: "far"
    distr_path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\Far30b6446.x64.msi"
    zip_name: ""
    exe_name: "Far.exe"
    path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\FAR"
    install: true
    install_script: "msiexec /i '{{ disk_install}}\\{{ antor_root_folder }}\\{{ distr_folder_host }}\\Far30b6446.x64.msi' /qn /norestart INSTALLDIR='{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\FAR'"
    shortcut: true
    icon_path: "{{ disk_install}}\\{{ antor_root_folder }}\\{{ antor_tools_folder }}\\FAR\\Far.exe"


